<a href="https://colab.research.google.com/github/Santosh123445/DMDW-lab/blob/main/18cse020ass2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
a=[int(i) for i in input().split()]
a=np.array(a)
a

2 5 8 9 


array([2, 5, 8, 9])

In [17]:
print(np.__version__)

1.18.5


In [18]:

print(type(a))

<class 'numpy.ndarray'>


In [19]:
#tuple to create array
a=np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [20]:
#create a 0-D array
a=np.array(10)
a

array(10)

In [21]:
#create a 1-D array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [22]:
#create a 2-D array
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [23]:
#create a 3-D array
a= np.array([[[11, 42, 53], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a)


[[[11 42 53]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [24]:
#check number of dimensions
a=np.array(10)
b=np.array([1,2,3,4,5,6])
c=np.array([[1, 2, 32], [4, 5, 6]])
d=np.array([[[1, 2, 322], [24, 52, 62]], [[31, 32, 43], [54, 65, 67]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [25]:
a = np.array([[14,223,34,42,45], [36,71,18,59,10]])
print('print 3 rd element of 1stdim', a[0, 3])


print 3 rd element of 1stdim 42


In [27]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', a[1, -1])

Last element from 2nd dim:  10


In [28]:
b = np.array([21, 52, 538, 84, 85, 76, 27])
print(b[1:5:2])

[52 84]


In [29]:

a= np.array(['apple', 'banana', 'cherry'])
print(a.dtype)

<U6


In [2]:
from google.colab import files
uploaded = files.upload()

Saving consumers-price-index-Sept20-seasonally-adjusted-csv-tables.csv to consumers-price-index-Sept20-seasonally-adjusted-csv-tables.csv


In [3]:
import io
df1 = pd.read_csv(io.BytesIO(uploaded['consumers-price-index-Sept20-seasonally-adjusted-csv-tables.csv']))

In [4]:
df1

Series_reference  ...       Series_title_1
0         CPIQ.SE9S01  ...  Seasonally adjusted
1         CPIQ.SE9S01  ...  Seasonally adjusted
2         CPIQ.SE9S01  ...  Seasonally adjusted
3         CPIQ.SE9S01  ...  Seasonally adjusted
4         CPIQ.SE9S01  ...  Seasonally adjusted
...               ...  ...                  ...
9814  CPIQ.SE9SNS6500  ...  Seasonally adjusted
9815  CPIQ.SE9SNS6500  ...  Seasonally adjusted
9816  CPIQ.SE9SNS6500  ...  Seasonally adjusted
9817  CPIQ.SE9SNS6500  ...  Seasonally adjusted
9818  CPIQ.SE9SNS6500  ...  Seasonally adjusted

[9819 rows x 8 columns]

In [5]:
df1.head

<bound method NDFrame.head of      Series_reference  ...       Series_title_1
0         CPIQ.SE9S01  ...  Seasonally adjusted
1         CPIQ.SE9S01  ...  Seasonally adjusted
2         CPIQ.SE9S01  ...  Seasonally adjusted
3         CPIQ.SE9S01  ...  Seasonally adjusted
4         CPIQ.SE9S01  ...  Seasonally adjusted
...               ...  ...                  ...
9814  CPIQ.SE9SNS6500  ...  Seasonally adjusted
9815  CPIQ.SE9SNS6500  ...  Seasonally adjusted
9816  CPIQ.SE9SNS6500  ...  Seasonally adjusted
9817  CPIQ.SE9SNS6500  ...  Seasonally adjusted
9818  CPIQ.SE9SNS6500  ...  Seasonally adjusted

[9819 rows x 8 columns]>

In [6]:
df1.shape

(9819, 8)

In [7]:
df1.columns

Index(['Series_reference', 'Period', 'Data_value', 'STATUS', 'UNITS',
       'Subject', 'Group', 'Series_title_1'],
      dtype='object')

In [8]:
df1.info

<bound method DataFrame.info of      Series_reference  ...       Series_title_1
0         CPIQ.SE9S01  ...  Seasonally adjusted
1         CPIQ.SE9S01  ...  Seasonally adjusted
2         CPIQ.SE9S01  ...  Seasonally adjusted
3         CPIQ.SE9S01  ...  Seasonally adjusted
4         CPIQ.SE9S01  ...  Seasonally adjusted
...               ...  ...                  ...
9814  CPIQ.SE9SNS6500  ...  Seasonally adjusted
9815  CPIQ.SE9SNS6500  ...  Seasonally adjusted
9816  CPIQ.SE9SNS6500  ...  Seasonally adjusted
9817  CPIQ.SE9SNS6500  ...  Seasonally adjusted
9818  CPIQ.SE9SNS6500  ...  Seasonally adjusted

[9819 rows x 8 columns]>

In [9]:
df1.describe()


Period    Data_value
count  9819.000000   9817.000000
mean   2011.502642    979.526339
std      10.357305    549.111401
min    1925.090000      0.000000
25%    2009.090000    878.000000
50%    2013.060000    979.000000
75%    2017.030000   1020.000000
max    2020.090000  11898.000000

In [10]:
df1.duplicated().sum()

0

In [11]:
df1.isnull().sum()

Series_reference    0
Period              0
Data_value          2
STATUS              0
UNITS               0
Subject             0
Group               0
Series_title_1      0
dtype: int64